### PR TITLE
chore: upgrade Android project to latest gradle

### PR DESCRIPTION
**Pull request by TheOneWithTheBraid**
- update metadata files
- delete deprecated metadata files
- correspondingly update .gitignores
- migrate Gradle to latest best practices
- update Gradle plugin
- update Kotlin
- remove dead Kotlin code

### CODE REVIEW

**Review by coder-with-a-bushido — APPROVED** [review]
LGTM :)

**Comment by coder-with-a-bushido** [comment]
@TheOneWithTheBraid Looks like your commit is not signed. Could you pls sign it and force push so I can merge?

**Comment by TheOneWithTheBraid** [comment]
> @TheOneWithTheBraid Looks like your commit is not signed. Could you pls sign it and force push so I can merge?

It *is* signed-off, PGP signed commits would be a new requirement for external contributors. Can you confirm this is now required for externals too, @krille-chan ?

**Comment by jcgruenhage** [comment]
We need to still clarify what signatures are made by whom: In my opinion, changes by external contributors should be *authored and signed-off* by the external contributor, but committed and therefore signed by a project maintainer.

That'd mean, that we're rebasing the branch ourselves, pushing it again, approving it afterwards and then merging it.

**Pull request merged**
